### ISSUE TITLE
Equation

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/HSPsquared#25]
### Tasks
- [x] Data Model in hdf5
- [x] Parser (json, UCI)
- [x] tokenize into solvable pieces
- [x] Object Model: class or functional? (see **Object Model** below)
- [x] #38
  - Decomposition/Run-time Optimization, can we split equation into individual 2 operand
  - ~eval():~ We cannot use `eval()` in `numba` - but maybe `numexpr.evaluate()` See below **Solver: eval options** 
  - Pre-rendered functions (see below **Solver: Pre-rendered Functions**

### Object Model
Explore method of using `@jitclass` objects or a more functional approach.
- https://numba.pydata.org/numba-doc/latest/user/jitclass.html#jitclass

### Handler Class

```
class Equation(modelObject):
    # the following are supplied by the parent class: name, log_path, attribute_path, state_path, inputs
    op_trios = [] # string array with sorted operand1, operand2, operator
    

test = Equation()
test.ncode_preStep() # generate the numba code for preStep() actions.

```

### Parser
- json coming in (already partially atomized and good for solving)

### Data Model in hdf5
- Referencing related variables. 
  - Ex: 
    - Entity: INTAKE_001, dhdf5 reference:  `/TIMESERIES/INTAKE_001/`
    - equation: `available_mgd = Qintake - flowby`
    - arguments:
      - Qreach: entity upstream flow + runoff in containing reach, `/TIMESERIES/RCHRES_001/IVOL` - could also be an equation scaling to intake drainage area, i.e. `Qreach = ivol * local_area / area`
      - flowby: local equation reference `/TIMESERIES/INTAKE_001/flowby/value` (note: flowby would also be an equation)
  - resolved out:
    - `ts['/TIMESERIES/INTAKE_001/available_mgd/value'] = ts['/TIMESERIES/RCHRES_001/IVOL/value'] - ts['/TIMESERIES/INTAKE_001/flowby/value']`
- With the above notation can we effectively create a matrix of mathematical during run prep, then execute those relationships very rapidly at runtime?
- Proposed Process:
   1. substitution: replace equation values with hdf5 paths
   2. retrieve: replace hdf5 paths with their values in the equation
   3. evaluate: do the math expression
   4. store: put data in relevant hdf5 location

#### Decomposition/Optimization:
  - Break into RPN type pieces _value_ and _operand_
  - Equation parser: https://levelup.gitconnected.com/how-to-write-a-formula-string-parser-in-python-5362210afeab

#### Eval
- `eval()` there are examples of using `numexpr.evaluate()` (a numba analog of `eval()`) with `@njit` however, 
  - it cannot accept array refrences in the equation, so, things like ` ts['/TIMESERIES/RCHRES_001/IVOL/value'] - ts['/TIMESERIES/INTAKE_001/flowby/value']` cannot be evaluated.
  - We would have to do a string substitution to replace the path with an actual value (like we did in `om`) BUT, the numba string replace methods do not allow replacing with a numeric value, only a string, and does not have the ability to convert a number to a string inside an `@njit` compiled function.

#### Pre-rendered Functions
  - At compile time, write out a function with a list of mathematical statements, like: `state['/STATE/INTAKE_001/available_mgd/value'] = state['/STATE/RCHRES_001/IVOL/value'] - state['/STATE/INTAKE_001/flowby/value']`
  - Could even have custom functions for each entity (but this would be a lot of overhead methinks, like:
    - `def fn_specl_rchres_0001_Qin(state, ui, ts, step)`

**Comment by rburghol** [comment]
Add a group with hdf5 module in python
```
import h5py
import pandas as pd
from collections import defaultdict
from pandas import DataFrame, read_hdf, HDFStore

fpath = '/c/Workspace/modeling/cbp/hsp2/river/OR1_7700_7980.h5' 
# close the already opened file first
f.close()
f = h5py.File(fpath,'a') # use mode 'a' which allows read, write, modify
objs = f.create_dataset("OBJECTS", (50,), dtype='f')
# made a mistake, need to create a group, not a dataset
del f["OBJECTS"]
grp = f.create_group("OBJECTS")
grp.create_group("RCHRES_0001")
rch = grp["RCHRES_0001"]
rch.create_group("Qin")
Qin = rch["Qin"]
# attributes can simply be added here:
Qin.attrs['equation'] = 'Qup * 1.23'
Qin.attrs['default_value'] = 0.0
Qin.attrs['state_path'] = "/STATE/RCHRES_0001/flowby"


```

**Comment by rburghol** [comment]
Now add a timeseries indexed by integers - `ts_ix`
```
ts_ix = Dict.empty(key_type=types.int64, value_type=types.float64[:])
tsq = f['TIMESERIES/']
ts_tables = list(tsq.keys())
for i in ts_tables:
    var_path = '/TIMESERIES/' + i
    ix = set_state(state_ix, state_paths, var_path, 0.0)
    dict(zip(tsq[i]['table']['index'], tsq[i]['table']['values']) )
    tdl = list(td.items())
    # doesn't work: (but we can use the internal hspf routines anyhow)
    ts_ix[ix] = np.asarray(tdl, dtype="float32")

```

**Comment by rburghol** [comment]
```
op_tokens, state_paths, state_ix, dict_ix = init_sim_dicts()

eqn_path = "/OBJECTS/RCHRES_0001/Qin"
eq_ix = set_state(state_ix, state_paths, eqn_path, 0.0) # initialize this equation operator in the state_ix Dict, returns unique key

# NR uses weird global shit so we have to do this:
exprStack = []
exprStack[:] = []
ps = deconstruct_equation(eqn)
