### ISSUE TITLE
modelObject: base class for object that has logging capabilities

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/HSPsquared#37]
### Tasks:
- [ ] Conceptual designs
- [ ] hsf5 Data Model
- [ ] #57
- [ ] model handler class
- [ ] execution rendering (`ncode_` functions)
- [ ] Logging

#### Main data storage
- `/OBJECTS/[name]/` contains all the properties in the model_object class, `log_path`, `attribute_path`, `state_path`, `inputs` (a local_name / path array) 
- Hierarchical, so subcomps can have subcomps, i.e.:
  - `/OBJECT/RCHRES_001/Qin`:
  - `/OBJECT/RCHRES_001/Qin/default_value`

```
class modelObject:
    name = "" # Ex: "Qin" 
    parent = False # will be a link to another object
    log_path = "" # Ex: "/RESULTS/RCHRES_001/SPECL" 
    attribute_path = "/OBJECTS/RCHRES_001" # 
    state_path = "" # Ex: "/STATE/RCHRES_001" # the pointer to this object state
    inputs = {} # associative array with key=local_variable_name, value=hdf5_path_of_source_variable_state
                      # like: [ 'Qin' : '/STATE/RCHRES_001/IVOL' ]
    
    def state_path(self):
        if not (self.parent == False):
            return self.parent.state_path() + "/" + self.name
        return "/STATE/" + self.name
    
    def find_var_path(self, var_name):
        if var_name in self.inputs.keys():
            return self.inputs[var_name]
        if not (self.parent == False):
            return self.parent.find_var_path(var_name)
        return False
    
    def add_input(self, var_name, var_path):
        # this will add to the inputs, but also insure that this 
        # requested path gets added to the state/exec stack via an input object if it does 
        # not already exist.

test = modelObject()
test.ncode_preStep() # generate the numba code for preStep() actions.

# ['ts["/RESULTS/RCHRES_002/SPECL/wd_mgd"][step] += ts["/RESULTS/RCHRES_001/SPECL/ps_refill_pump_mgd"][step]', 'ts["/RESULTS/RCHRES_002/SPECL/Qtrib"][step] += ts["/RESULTS/RCHRES_001/SPECL/Qout"][step]']

```

**Comment by rburghol** [comment]
```
ts_ix = Dict.empty(key_type=types.int64, value_type=types.float32[:])
tsq = f['TIMESERIES/']
ts_ts = np.asarray(tsq['TS011']['table']['index']) # index of timestamps for each timestep. use known TS for this demo
# this code replicates a piece of the function of get_timeseries, and loads the full timeseries into a Dict
# the dict will be keyed by a simple integer, and have values at the time step only.  The actual time 
# at that step will be contained in ts_ts 
ts_tables = list(tsq.keys())
for i in ts_tables:
    if i == 'SUMMARY': continue # skip this non-numeric table
    var_path = '/TIMESERIES/' + i
    ix = set_state(state_ix, state_paths, var_path, 0.0)
    ts_ix[ix] = np.asarray(tsq[i]['table']['values'], dtype="float32")


river = modelObject()
river.state_path = "/STATE/RCHRES_001"
river.inputs["Qin"] = ["/TIMESERIES/TS011"]
# alternative, using STATE: river.inputs["Qin"] = ["/STATE/RCHRES_001/HYDR/IVOL"]
river.inputs["ps_mgd"] = ["/TIMESERIES/TS3000"]

Qintake = Equation()
Qintake.parent = river

```
