### ISSUE TITLE
ModelLinkage: multi purpose method of linking local and remote data

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/HSPsquared#44]
### Tasks
- [ ] Can/should we use SCHEMATIC or MASSLINK for model data passing like in the old framework?
- [ ] What are requirements for setting data?
- [ ] Where in the hsp2 code is data from these passed and set?
- [ ] Final Data Model

### Overview
These are connections
- See code: https://github.com/HARPgroup/HSPsquared/blob/specom/HSP2/om_model_linkage.py
- remote connections can be context sensitive.  That is, in a sequential simulation (like standard HSPF) anything outside a given rchres is remote, but in a simultaneous solution they might not be.
  - remote: data would be obtained from the timeseries `/RESULTS/xxxx`
  - local: data would be obtained from the state `/STATE/xxxx`
  - maybe the decision on local/remote can be made either at declaration time, or, by the module invoking specl, so it automatically looks for state or ts depending?
  - can we include the path to model attribute in hdf5, then let the ts/state decision be made via code?

#### OM Inputs (old model)
- *OM inputs*: these are not an object class, but rather they are a set of stored object references, which we will likely replace with references to the global data store/dictionary
  - Old model used `addInput()` function, and `inputs[]` array to store links to other object data (read only). How to replicate this?

#### Data Model
- consider ts['/links/table'] like from_node, to_node, src_prop, dest_prop
  - Better to set these as `/objects/system/...`
- A water facility could store it's state table data in `/objects/system/[hydroid]/...`,
