### ISSUE TITLE
HSP2 Python Implementation of HSPF

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/HSPsquared#5]
Development main tracking here.  Live issue on $hsp^2$ is: https://github.com/respec/HSPsquared/issues/90

### Overview
This issue is set up to plan and track development for a proposed "SPEC-ACTIONS" module in hsp2. Development has 2 main components:
1. Provide support for pre-hsp2 uci files that use SPEC-ACTIONS
2. Provide an enhanced "next generation" type implementation for SPEC-ACTIONS

### Tasks 
- [x] Add initial outline in hsp2 repo
  - [x] Where/when are Special actions called:
  - [x] When are Special actions called:
- [ ] Identify priorities for development
- [ ] Begin coding data model, object classes.

### Reference
- Version 12.2 fortran Special Actions code
  - `specact.f`/ `SPECACT.FOR`: subroutines for parsing and executing special actions
    - PSPECL: process the special actions block [lib3.0/SRC/HSPF122/Specact.FOR](https://github.com/respec/FORTRAN/blob/master/lib3.0/SRC/HSPF122/Specact.FOR)
    - Execute SPEC-ACTIONS: https://github.com/respec/FORTRAN/blob/ae3b77117872a8625b1dc2ab51c0a4b48ddd411b/lib3.0/SRC/HSPF122/Specact.FOR#L4696
  - HSPF: the main executable for HSPF [hspf/lib3.2/src/hspf/hspf.f](https://github.com/respec/FORTRAN/blob/master/lib3.0/SRC/HSPF122/HSPF.FOR)
  - Special actions called: https://github.com/respec/FORTRAN/blob/ae3b77117872a8625b1dc2ab51c0a4b48ddd411b/lib3.0/SRC/HSPF122/HOSUPER.FOR#L290

**Comment by rburghol** [comment]
Find the HYDR routine in the old code base: 
`fgrep "HYDR" /opt/model/p53/p532c-sova/code/src/* -R|grep -i subroutine`

**Comment by jdkleiner** [comment]
Next Steps 11/9/22

-
